version: "3.7"
services:
  client:
    image: pico-frontend
    ports:
      - "8070:3000"
    restart: always
    container_name: pico-frontend
    networks:
      - pico
volumes:
  db:
networks:
  pico:
    driver: bridge
  caddy-external:
    external: true
